# The Docker image that will be used to build your app


build-documentation:
  image: ubuntu:noble
  before_script:
    - apt update
    - apt install -y build-essential cmake doxygen graphviz
  script:
    - echo "Rendering HTML..."
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target docs_target
  artifacts:
      paths:
        - build/cmake_generated/html/


pages:
  dependencies:
    - build-documentation
  script:
  - mv build/cmake_generated/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

 

