@startuml inline_umlgraph_1.png
component Client
component Invoker

interface Receiver
component ContainerReceiver
component SingleReceiver

interface Command
component CreateCommand
component ReadCommand
component UpdateCommand
component DeleteCommand

Command <|.up. CreateCommand
Command <|.up. ReadCommand
Command <|.up. UpdateCommand
Command <|.up. DeleteCommand

Receiver <|.down. ContainerReceiver
Receiver <|.down. SingleReceiver

Client <- Receiver : Get Response
Command -down-> Receiver : Operation params
Client -up-> Invoker : Set Command
Invoker -> Command : Initiate request
@enduml
@startuml inline_umlgraph_2.png
component Client
component Invoker

interface Receiver
component ContainerReceiver
component SingleReceiver

interface Command
component CreateCommand
component ReadCommand
component UpdateCommand
component DeleteCommand

Command <|.up. CreateCommand
Command <|.up. ReadCommand
Command <|.up. UpdateCommand
Command <|.up. DeleteCommand

Receiver <|.down. ContainerReceiver
Receiver <|.down. SingleReceiver

Client <- Receiver : Get Response
Command -down-> Receiver : Operation params
Client -up-> Invoker : Set Command
Invoker -> Command : Initiate request
@enduml
