name: Doxygen Action

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment     
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake    
      shell: bash
      working-directory: ${{github.workspace}}/build   
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --target docs_target

    - name: Deploy
      working-directory: ${{github.workspace}}/build
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cmake_generated/html